---
title: "Week 2 - Functional Musculoskeletal Testing"
subtitle: "Assessments for Complex Cases and Special Populations"
---

{{< pagebreak >}}

## Pre-Lab Activity

Please complete the brief quiz to refresh your thinking about some general concepts covered in Exercise Physiology. This quiz is also available in your Canvas modules.

Please also watch the Canvas content on the profession of Accredited Exercise Physiology.

1.  An exercise contraindication is defined as:\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

2.  Training for hypertrophy focuses on the concept of time-under-\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ and uses an approximate rep/set range of \_\_\_\_\_\_\_\_-\_\_\_\_\_\_\_\_ sets of \_\_\_\_\_\_\_\_-\_\_\_\_\_\_\_\_ reps

3.  List at least 4 factors that are defined as positive risk factors in the risk stratification profile\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

4.  Subjective ratings of exertion can be assessed via the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ scale which was devised by \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_. There are two commonly used scales, with one scale ranging from \_\_\_\_\_\_\_\_-\_\_\_\_\_\_\_\_ and the other ranging from \_\_\_\_\_\_\_\_-\_\_\_\_\_\_\_\_.

5.  Stretching has been demonstrated to conclusively improve exercise performance\
    TRUE / FALSE

6.  Blood pressure is assessed by listening for the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ sounds. A ‘normal’ blood pressure score is \_\_\_\_\_\_\_\_/\_\_\_\_\_\_\_\_ whereas a ‘borderline high’ score is \_\_\_\_\_\_\_\_/\_\_\_\_\_\_\_\_.

7.  FITT stands for \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_.

8.  A BMI score of 34.2 is classed as \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

9.  For a given power output, the Heart Rate response will be HIGHER / LOWER for upper body exercise when compared to lower body exercise.

10. An electrocardiogram provides information about:\
    \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

{{< pagebreak >}}

## Lab Session

### Introduction

There are many different methods to assess strength and functional capacity in individuals with chronic diseases. The gold standard of strength and power assessment is performed on an isokinetic dynamometer. You may have witnessed testing on this device previously (in 92533 Exercise Physiology) or and have seen footage of this testing procedure for different joints of the body. It is possible to determine strength at certain velocities and certain angles which are related to performance in numerous tasks. Further, by looking at rate of force development, exercise scientists can examine power output which is strongly related to exercise performance and risk of falling.

In addition to the examination of strength and power, it is important to determine functional capacity. Functional capacity is integrally related to quality of life, and is perhaps a stronger indicator of life satisfaction than specific measures of muscle strength. There are unique tests that can monitor balance, the ability to rise from a chair, walking performance, stair climbing ability and many other facets of daily life. In today’s lab, you will perform some different types of tests that relate to functional performance, and also look at some methods to improve performance in these tests.

#### Assessment of functional ability in special populations

Functional performance is proportionally related to quality of life. There are many ways that exercise scientists can assess functional performance in special populations. One must consider the intensity of the testing and the actions undertaken, however, these types of tests are typically of a lower intensity than traditional tests such as maximal treadmill tests, and therefore safety is less of a concern. Regardless, it is still important to complete the appropriate screening questionnaires and obtain informed consent to participate. Correct technique can be an issue, especially in frail individuals, however, the simple nature of the tests generally permit high levels of reliability and validity.

{{< pagebreak >}}

### Methods

#### Equipment

-   Cones x 5
-   Stopwatches x 15
-   Chairs x 3
-   Measuring tape

#### Tests

The following tests are examples of methods to assess functional capacity and could be used for any sub-population, especially those who are frail, have a chronic disease or a disability.

##### 1.6 km Walk Test

To estimate VO2max and investigate self-selected walking speed, a 1.6 km walk test has been shown to be valid and reliable. It is typically conducted around a standard 400 m grass athletic oval. Participants are instructed to cover the distance “walking as fast as comfortably possible.” This test is often selected as exertions of this intensity are ideal for individuals with chronic diseases and older adults. Heart rate is recorded at the completion of the walk, along with time to complete the distance. Average walking speed may be calculated for analytical and comparative purposes. VO2max can be reliably estimated from the 1.6 km walking test, with the following equation shown to yield the least standard error (0.325 L/min; Kline et al., 1987):

> *VO~2~max (L/min) = 6.9652 + (0.0091 × body mass) – (0.0257 × age) + (0.5955 × gender\[female=0, male=1\]) – (0.2240 × time) – (0.0115 × heart rate)*

The reliability of this test has been previously established (r=0.71–0.97) among many age groups.

##### Sit-to-Stand Test

The sit-to-stand (STS) test measures the time taken to rise from a chair (and sit back down) five times, as fast and as safely as possible (Runge et al., 2000). This test is administered on a chair without arms and a seat height of approximately 40 cm. The chair is fixed to the ground to avoid movement during the test. A standardized position is used for each test that includes being seated in the middle of the chair, back straight, arms folded across the chest, and feet approximately shoulder width apart. A total of three trials are generally performed with 2 min rest between trials with the mean of the best two trials used for analysis. The total time is often measured using pressure pads fixed to the seat, with results recorded and calculated on a computer after each trial. The repeatability of this test is excellent, with interday reliability of the STS test being 0.96. A recent appraisal of the STS test compared to a leg press exercise demonstrated the functionality of the assessment (Alcazar et al., 2018).

##### Timed-Up and Go-Test

The timed-up and go-test (TUG) involves standing up from a chair, walking 3 m as quickly and as safely as possible, crossing a line marked on the floor, turning around, and then walking back to sit back down in the chair (Bruyere et al., 2005). The participant is initially seated in a 40 cm-high chair without arms, with his or her back flush against the backrest. The time taken is typically calculated by pressure pads secured to the centre of the seat. Turning time, the time to turn around at the 3-m mark can also be measured if that measure is of interest to the tester. The researcher gives a verbal cue to begin the test, and the times for three trials are recorded, with 2 min rest between trials. The mean of the best two trials is used for analysis. This test also displays excellent interday reliability, with intraclass correlations of the TUG test being 0.90.

##### Fast Walk

This test requires participants to walk as fast as possible over 10 m. The time taken is calculated using timing gates positioned at 5-m and 10-m intervals from the start line. The starting position involves feet placed together, 30 cm behind the first timing gate. Once ready, participants are allowed to commence the test at their own discretion. It is a requirement of the walking test that one foot be kept in contact with the ground at all times (to prevent running). Three fast-walk trials are usually performed, with a 2 min rest period between trials. The mean of the two best trials is used for analysis. Interday reliabilities of the 5-m and 10-m fast-walk test are 0.95 and 0.98, respectively.

##### Stair Mobility Test

The stair mobility task involves participants climbing and descending five steps (approximately 20 cm high and 25 cm deep). The test measures the time taken to complete this task twice. Participants are required to ascend and descend one stair at a time and avoid using a handrail. Stair mobility can be assessed by a video camera (recording at 50 Hz) placed 2 m perpendicular to the stairs. In this manner, contact time on each step can be assessed. In today’s lab, you will not be assessing the contact time, rather, you will just assess the total time to complete the task. A total of three trials are generally conducted, with a 2-min rest period between efforts. Interday reliability of the stair mobility task is 0.98.

##### One-Legged Postural-Steadiness / 3-Dimensional Balance Assessment

One legged postural steadiness (OLPS) is assessed during a one-legged stance, analysing the patterns of ground reaction force variability. The starting position involves feet being placed shoulder width apart with weight evenly distributed and eyes facing forward. The subjects are instructed to stand for as long as possible (up to 15 sec) during OLPS, attempting to keep arms by the body for balance. The participants are informed that a touchdown by the non-stance leg is acceptable, yet should be corrected immediately. A touchdown on the force platform contributes to the force variability, which is consistent with using variability of the signal to quantify postural steadiness. Three trials of OLPS are usually completed for both legs. The ground reaction forces are measured on a three-dimensional force plate, with 2 forces measured: medial/lateral and vertical. As the initial weight transfer occurs laterally, anterior/posterior forces are disregarded.

To enable comparisons between subjects, the amplitude of each force signal is normalized for body mass, expressed as a percentage of body weight (%BW). The variability of forces during OLPS is analysed as the mean and standard deviation of these force signals during five intervals: 1) 0-0.49 sec; 2) 0.5-0.99 sec; 3) 1-4.99 sec; 4) 5-9.99 sec; 5) 10-15 sec (Jonsson et al., 2005). The test-retest reliability of OLPS has been reported to be 0.78 for vertical and 0.79 for lateral force variability (Rees et al., 2008).

Note: In today’s lab, we will not be performing OLPS testing, due to the complex nature of the analysis.

##### 15-second Balance Assessment

This test involves shifting the body mass in an anterior/posterior plane, and examines the number of times an individual requires the use of the non-testing leg to regain balance. The subject commences standing with feet shoulder width apart and weight evenly distributed. They step forward approximately 30 cm and transfer their mass to one leg, and remain on one leg for as long as possible (up to a maximum of 15 sec). If the subject loses their balance, they are permitted to briefly touch down on the ground with their non-stance foot to regain postural control. The number of ground touches of the non-stance foot are counted and recorded. Further, the time elapsed until the first touch down is recorded, as this is noted as being significantly related to falls risk. The test is performed with eyes open in the first instance, and repeated with eyes closed (eyes closed condition is only undertaken by capable subjects).

##### Other tests

There are many other functional tests to be found in the literature. You might come across the 6 minute walking test, tandem stand, the centre-of-pressure test, overhead reaching, Functional Movement Screen, ladder climb, tandem backwards walk, floor rise to standing, functional reach test, and many others. Research that examines their validity and reliability is abundant and there are many applications across a range of non-healthy clients.

{{< pagebreak >}}

### Results

In small groups, conduct each of the tests and record your results below.

#### Activity: Conducting Tests

##### Dynamic Tests

| Test                          | Trial 1 (secs) | Trial 2 (secs) |
|-------------------------------|----------------|----------------|
| Sit-to-Stand                  |                |                |
| Timed Up and Go               |                |                |
| 10m Fast Walk (5-metre time)  |                |                |
| 10m Fast Walk (10-metre time) |                |                |
| Stair Test                    |                |                |

: {.striped .hover}

##### 15-second Balance Tests

| Trial | Trial 1 (Foot Touchdowns) | Trial 2 (Foot Touchdowns) |
|----|----|----|
| Right Foot, Eyes Open |  |  |
| Left Foot, Eyes Open |  |  |
| Right Foot, Eyes Closed |  |  |
| Left Foot, Eyes Closed |  |  |

: {.striped .hover}

::: {.callout-note appearance="simple"}
## Circle/highlight the best trial result in each test
:::

##### 1.6km Walk Test

In the interest of time, you do not need to complete this test during the lab (typical duration 10-16 minutes). You can use the following values to calculate the estimated VO~2max~ using the equation above.

|  |  |  |  |  |  |  |
|----|----|----|----|----|----|----|
| **Mass (kg)** | **Age (yr)** | **Gender \[0/1\]** | **Time (min)** | H**R (bpm)** | **EstVO~2max~ (absolute - L.min^-1^)** | **EstVO~2max~ (relative - ml.kg^-1^.min^-1^)** |
| 77 | 54 | 1 | 13:45 | 137 |  |  |
|  |  |  |  |  |  |  |

: {.striped .hover}

{{< pagebreak >}}

### Discussion

1.  Which of the tests that you performed today would exhibit correlations/relationships between each other?\
    \
    \
    \
    \
    \

2.  List some of the limitations when performing the 15 sec eyes open/closed balance tests.\
    \
    \
    \
    \
    \

3.  What are the benefits of performing the 6-minute walk test over the 1.6km walk test? What are the limitations?\
    \
    \
    \
    \
    \

4.  How does muscle strength relate to functional performance and the performance of activities of daily living?\
    \
    \
    \
    \
    \

5.  How does muscle power relate to the risk of falling?\
    \
    \
    \
    \
    \
